model:
  channels: 32
  num_blocks: 7
  semantic_classes: 4
  instance_classes: 4
  sem2ins_classes: []
  semantic_only: True
  ignore_label: -100
  grouping_cfg:
    score_thr: 0.2
    radius: 0.04
    mean_active: 300
    class_numpoint_mean: [52209, 3975, 17472, 219035]
    npoint_thr: 0.05  # absolute if class_numpoint == -1, relative if class_numpoint != -1
    ignore_classes: []
  instance_voxel_cfg:
    scale: 50
    spatial_shape: 20
  train_cfg:
    max_proposal_num: 200
    pos_iou_thr: 0.5
  test_cfg:
    x4_split: True
    cls_score_thr: 0.001
    mask_score_thr: -0.5
    min_npoint: 100
    eval_tasks: ['semantic']
  fixed_modules: []

data:
  train:
    dowsample_ratio: 0.25
    type: 'telco'
    data_root: 'dataset/telco'
    prefix: ['Area_1']
    suffix: '.pth'
    repeat: 20
    training: True
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
  test:
    dowsample_ratio: 1.0
    type: 'telco'
    data_root: 'dataset/telco'
    prefix: ['Area_0']
    suffix: '.pth'
    training: False
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000

dataloader:
  train:
    batch_size: 4
    num_workers: 4
  test:
    batch_size: 1
    num_workers: 1

optimizer:
  type: 'Adam'
  lr: 0.004

fp16: False
epochs: 20
step_epoch: 0
save_freq: 2
pretrain: 'tmp/hais_ckpt_spconv2.pth'
work_dir: ''
