model:
  channels: 32
  num_blocks: 7
  semantic_classes: 5
  instance_classes: 4
  sem2ins_classes: []
  semantic_only: True
  ignore_label: -100
  grouping_cfg:
    score_thr: 0.2
    radius: [0.04, 0.045, 0.01, 0.04, 0.04]
    mean_active: 300
    class_numpoint_mean: [203076, 3000, 993, 4368, 54758]
    npoint_thr: 0.05  # absolute if class_numpoint == -1, relative if class_numpoint != -1
    ignore_classes: [0]
  instance_voxel_cfg:
    scale: 50
    spatial_shape: 100
  train_cfg:
    max_proposal_num: 100
    pos_iou_thr: 0.5
  test_cfg:
    x4_split: True
    cls_score_thr: 0.001
    mask_score_thr: -0.5
    min_npoint: 100
    eval_tasks: ['semantic']
  fixed_modules: []

data:
  train:
    downsample_ratio: 0.25
    type: 'telco'
    data_root: '/home/abdulbasit/Desktop/utils/abdul_basit_data/poc_dataset_softgroup_fmt/all_patch_train_val'
    prefix: ['Area_ftrain']
    suffix: '.pth'
    repeat: 20
    training: True
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 180000
      min_npoint: 5000
  test:
    downsample_ratio: 1.0
    type: 'telco'
    data_root: '/home/abdulbasit/Desktop/utils/abdul_basit_data/poc_dataset_softgroup_fmt/all_patch_train_val'
    prefix: ['Area_fval']
    suffix: '.pth'
    training: False
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 180000
      min_npoint: 5000

dataloader:
  train:
    batch_size: 3
    num_workers: 3
  test:
    batch_size: 1
    num_workers: 1

optimizer:
  type: 'Adam'
  lr: 0.008

fp16: False
epochs: 30
step_epoch: 0
save_freq: 2
pretrain: 'tmp/hais_ckpt_spconv2.pth'
work_dir: ''
